function T=FK_join_z(Tbase,d,q,theta,L,Ttool)
 T=(Tbase*Tz(d)*Tz(theta(1))*Rz(q(1))*Tx(L(1))*...
    Tx(theta(2))*Ty(theta(3))*Tz(theta(4))*Rx(theta(5))*Ry(theta(6))*Rz(theta(7))*...
    Rz(q(2))*Tx(L(2))*...
    Tx(theta(8))*Ty(theta(9))*Tz(theta(10))*Rx(theta(11))*Ry(theta(12))*Rz(theta(13))*....
    Rz(q(3))*Ttool);

end




